export const labels = {
  en: {
    language: "Language",
    transactions: "Transactions",
    totaltransactions:"Total Transactions",
    mmkreceived:"MMK RECEIVED (SELL)",
    mmkreceivedmobile:"Mobile IN (SELL)",
    mmkpaidout:"MMK PAID OUT (BUY)",
    mmkpaidoutmobile:"Mobile out (BUY)",
    mobileNet:"Mobile Net",

    cashTotal:"Cash Total",
    cashNet:"Cash Net",
    mobileTotal:"Mobile Total",
    dailyLog:"Daily Log",

    saveOpening:"Save Opening",
    saveClosing:"Save Closing",
    openingMMK:"Opening Cash (MMK)",
    closingMMK:"Closing Cash (MMK)",    
    pl:"CASH Profit/Loss",
    openingMMKmobile:"OPENING MOBILE (MMK)",
    closingMMKmobile:"Closing Mobile (MMK)",
    cashLeft:"Cash Left (MMK)",
    mobileLeft:"Mobile Left (MMK)",
    plmobile:"Mobile Profit/Loss",
    totalpl:"Total Net",
    greenP:"green = profit",
    redL:"red = loss",

    newTransaction: "New Transaction",
    balances: "Balances",
    dailyReport: "Daily Report",
    monthlyReport: "Monthly Report",
    yearlyReport: "Yearly Report",
    reports:"Reports",

    foreign_currencies:"Foreign Currencies",
    editableRows:"Editable rows",
    unsavedChanges:"Unsaved Changes",
    addCurrency:"Add Currency",

    logout: "Logout",
    refresh: "Refresh",
    print: "Print",
    save: "Save",
    closeDay: "Close Day",
    reopenDay: "Re-open Day",   

    date:"Date",
    fx_balances:"Fx balances",
    buy:"BUY",
    sell:"SELL"
  },
  
  mm: {
    language: "ဘာသာစကား",
    transactions: "အရောင်းအ၀ယ်စာရင်း",
    totaltransactions:"စုစုပေါင်းအရောင်းအ၀ယ်အရေအတွက်",
    mmkreceived:"စုစုပေါင်း၀င်ငွေ",
    mmkreceivedmobile:"စုစုပေါင်း၀င်ငွေ mobile",
    mmkpaidout:"စုစုပေါင်းထွက်ငွေ",
    mmkpaidoutmobile:"စုစုပေါင်းထွက်ငွေ mobile",
    mobileNet:"စုစုပေါင်းအမြတ် Mobile",

    cashTotal:"စုစုပေါင်းလက်ရှိငွေ",  
    cashNet:"စုစုပေါင်းအမြတ်ငွေ Cash",  
    mobileTotal:"mobile banking စုစုပေါင်း",    
    dailyLog:"အရောင်းအ၀ယ်များ",

    saveOpening:"စဖွင့်ငွေ",
    saveClosing:"ပိတ်ငွေ",
    openingMMK:"စဖွင့်ငွေ",
    closingMMK:"စာရင်းပိတ်ကျန်ငွေ",
    cashLeft:"လက်ကျန်ငွေ",
    mobileLeft:"Mobile Banking လက်ကျန်ငွေ",
    pl:"အမြတ်အရှုံး cash",
    openingMMKmobile:"စဖွင့်ငွေ mobile",
    closingMMKmobile:"စာရင်းပိတ်ကျန်ငွေ mobile",
    plmobile:"အမြတ်အရှုံး mobile",
    totalpl:"အမြတ်အရှုံး",
    greenP:"အစိမ်း = အမြတ်",
    redL:"အနီ = အရှုံး",

    newTransaction: "အရောင်းအဝယ်အသစ်",
    balances: "နေ့စဉ်စာရံငွေသတ်မှတ်မည်",
    dailyReport: "နေ့စဉ်စာရင်း",
    monthlyReport: "လစဉ်စာရင်း",
    yearlyReport: "နှစ်စဉ်စာရင်း",
    reports:"နှစ်/လ/နေ့စဉ် စာရင်းချုပ်",

    foreign_currencies:"နိုင်ငံခြားငွေ",
    editableRows:"ပြုပြင်လို့ရသော Currency",
    unsavedChanges:"save မလုပ်ရသေးသော Currency",
    addCurrency:"Currency အသစ်ထည့်ရန်",

    logout: "ထွက်မည်",
    refresh: "___",
    print: "___",
    save: "___",
    closeDay: "ဆိုင်ပိတ်မည်",
    reopenDay: "ပြန်ဖွင့်မည်",

    date:"ရက်စွဲ",
    fx_balances:"လက်ရှိ နိုင်ငံခြားငွေ",
    buy:"၀ယ်သည်",
    sell:"ရောင်းသည်"

  },
};